apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-development
  namespace: argocd
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/part-of: platform-launchpad
    app.kubernetes.io/environment: development

spec:
  project: default

  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.14.0
      helm:
        releaseName: aws-load-balancer-controller
        valueFiles:
          - $values/platform/aws-load-balancer-controller/development-values.yaml

    - repoURL: https://github.com/xtinead/platform-launchpad-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true