apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: platform-launchpad
  labels:
    app.kubernetes.io/name: platform-launchpad-backend
    app.kubernetes.io/part-of: platform-launchpad
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: platform-launchpad
  labels:
    app.kubernetes.io/name: platform-launchpad-worker
    app.kubernetes.io/part-of: platform-launchpad
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
