apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-launchpad
  namespace: platform-launchpad
  labels:
    app.kubernetes.io/name: platform-launchpad
    app.kubernetes.io/part-of: platform-launchpad
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb

  rules:
    - host: launchpad.christineadelusi.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /openapi.json
            pathType: Exact
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000